// ============================================================
// MOCK DATA — Walid Mostfaoui Portfolio
// ============================================================

export const PERSON = {
  name: 'Walid Mostfaoui',
  title: 'E-Commerce Strategist & Growth Operator',
  tagline: "I don't just sell products — I build revenue machines.",
  bio: `Walid is a seasoned e-commerce operator with over 5 years of hands-on experience scaling brands across fashion, electronics, and consumer goods. He has built and managed high-converting Shopify and WooCommerce stores, run profitable TikTok Shop campaigns, and mastered the full dropshipping supply chain — from product sourcing to post-purchase optimization. He works with brands that want to go from 0 to profitable, fast.`,
  location: 'Algeria — working globally',
  email: 'walid@mostfaoui.com',
  whatsapp: '+213 XX XX XX XX',
  instagram: '@walidmostfaoui',
};

export const METRICS_HERO = [
  { label: 'Revenue Generated', value: 2.4, suffix: 'M+', prefix: '$', decimals: 1 },
  { label: 'Average ROAS', value: 4.7, suffix: 'x', decimals: 1 },
  { label: 'Stores Built', value: 23, suffix: '+', decimals: 0 },
  { label: 'Years Experience', value: 5, suffix: '+', decimals: 0 },
];

export const METRICS_ALL = [
  { label: 'Revenue Generated', value: 2.4, suffix: 'M+', prefix: '$', decimals: 1, context: 'Total across all managed stores' },
  { label: 'Ad Spend Managed', value: 380, suffix: 'K+', prefix: '$', decimals: 0, context: 'Meta, TikTok & Google' },
  { label: 'Average ROAS', value: 4.7, suffix: 'x', decimals: 1, context: 'Across all ad accounts' },
  { label: 'Stores Built & Scaled', value: 23, suffix: '+', decimals: 0, context: 'Shopify & WooCommerce' },
  { label: 'Products Tested', value: 1200, suffix: '+', decimals: 0, context: 'Across all niches' },
  { label: 'Countries Sold In', value: 17, suffix: '', decimals: 0, context: 'Global reach' },
  { label: 'Years of Experience', value: 5, suffix: '+', decimals: 0, context: 'Full-time e-commerce' },
  { label: 'Client Satisfaction', value: 98, suffix: '%', decimals: 0, context: 'Based on 50+ projects' },
];

export const SKILLS = [
  'Meta Ads', 'TikTok Ads', 'Google Shopping', 'Product Research',
  'WooCommerce', 'Shopify', 'Brand Strategy', 'Dropshipping',
  'CRO', 'TikTok Shop', 'UGC Creatives', 'Email Marketing', 'Analytics',
];

export const SERVICES = [
  {
    id: 'ads',
    icon: 'TrendingUp',
    title: 'Paid Traffic & Ads Management',
    description: 'Meta Ads, TikTok Ads, and Google Shopping — end-to-end campaign management. From creative strategy and audience targeting to scaling profitable ad sets.',
    tag: 'Meta · TikTok · Google',
    highlight: 'Avg 4–6x ROAS',
  },
  {
    id: 'research',
    icon: 'Search',
    title: 'Product Research & Validation',
    description: 'Deep-dive market research using Minea, AdSpy, and TikTok Creative Center. I identify winning products before they trend, with a proprietary scoring system.',
    tag: 'Minea · AdSpy · TikTok CC',
    highlight: 'Proprietary scoring system',
  },
  {
    id: 'brand',
    icon: 'Layers',
    title: 'Brand Strategy & Positioning',
    description: 'Building e-commerce brands that feel premium — from naming, logo direction, color identity, to tone of voice and store design philosophy.',
    tag: 'Branding · Design · UX',
    highlight: 'Full brand identity',
  },
  {
    id: 'store',
    icon: 'ShoppingBag',
    title: 'Store Setup & Optimization',
    description: 'Full store builds with CRO baked in — fast-loading themes, trust signals, upsell flows, abandoned cart sequences.',
    tag: 'Shopify · WooCommerce',
    highlight: 'CRO-optimized builds',
  },
  {
    id: 'tiktok',
    icon: 'Play',
    title: 'TikTok Shop Growth',
    description: 'Full organic + paid TikTok Shop strategy: product listing optimization, affiliate outreach, short-form video brief creation, and shop scaling playbook.',
    tag: 'TikTok Shop · Organic',
    highlight: '0 → 2K orders in 6 weeks',
  },
  {
    id: 'dropship',
    icon: 'Package',
    title: 'Dropshipping Systems',
    description: 'End-to-end dropshipping setup: supplier sourcing, order automation, fulfillment chain, dispute handling, and scaling playbook documentation.',
    tag: 'Automation · Systems',
    highlight: 'Full-stack operation',
  },
];

export const CASE_STUDIES = [
  {
    id: 'fashiondrop',
    slug: 'fashiondrop-co',
    brand: 'FashionDrop.co',
    niche: "Women's Fashion",
    platform: 'Shopify + Meta Ads',
    result: 'Scaled from $0 to $87K/month',
    period: '4 months',
    roas: '5.2x',
    roasLabel: 'ROAS on Meta',
    strategy: 'Influencer-style UGC creatives + Lookalike audience stacking',
    accentColor: '#F97316',
    metrics: [
      { label: 'Monthly Revenue', value: '$87K' },
      { label: 'Time Frame', value: '4 months' },
      { label: 'ROAS', value: '5.2x' },
    ],
    problem: "Brand new store with zero brand awareness, launching into a competitive women's fashion accessories market.",
    strategyDetail: 'Developed influencer-style UGC creative briefs, built lookalike audiences from early customers, and implemented a full funnel from awareness to conversion.',
    resultsDetail: 'Grew from $0 to $87,000 monthly revenue within 4 months. Achieved 5.2x ROAS on Meta with a blended ROAS of 4.8x.',
  },
  {
    id: 'gadgetflow',
    slug: 'gadgetflow-dz',
    brand: 'GadgetFlow DZ',
    niche: 'Consumer Electronics',
    platform: 'WooCommerce + Google',
    result: '340% revenue increase',
    period: '90 days',
    roas: '4.3x',
    roasLabel: 'ROAS on Google',
    strategy: 'Structured Google Shopping feed + competitor pricing strategy',
    accentColor: '#4285F4',
    metrics: [
      { label: 'Revenue Increase', value: '+340%' },
      { label: 'Time Frame', value: '90 days' },
      { label: 'ROAS', value: '4.3x' },
    ],
    problem: 'Struggling WooCommerce store in a competitive electronics niche, losing to bigger players on Google Shopping.',
    strategyDetail: 'Rebuilt Google Shopping product feed from scratch, implemented competitive pricing strategy, and restructured ad campaigns by product category.',
    resultsDetail: '340% revenue increase in just 90 days. Google Shopping became the primary revenue channel with 4.3x ROAS.',
  },
  {
    id: 'trendvault',
    slug: 'trendvault',
    brand: 'TrendVault',
    niche: 'Viral Lifestyle',
    platform: 'TikTok Shop',
    result: '3 products hit $10K+ in week 1',
    period: '6 weeks',
    roas: '6.1x',
    roasLabel: 'Blended ROAS',
    strategy: 'Affiliate seeding + daily creative testing system',
    accentColor: '#EC4899',
    metrics: [
      { label: 'Week 1 Revenue', value: '$30K+' },
      { label: 'Time Frame', value: '6 weeks' },
      { label: 'Blended ROAS', value: '6.1x' },
    ],
    problem: 'Entering TikTok Shop with zero presence in a crowded viral products space.',
    strategyDetail: "Built an affiliate seeding program with 50+ micro-creators, implemented daily creative testing, and optimized product listings for TikTok's algorithm.",
    resultsDetail: '3 products hit $10,000+ in their first week. 2,000+ orders in 6 weeks. 6.1x blended ROAS.',
  },
  {
    id: 'luxehome',
    slug: 'luxehome-store',
    brand: 'LuxeHome Store',
    niche: 'Home Décor & Living',
    platform: 'Shopify + TikTok Ads',
    result: '$220K revenue in 6 months',
    period: '6 months',
    roas: '4.1x',
    roasLabel: 'Avg ROAS',
    strategy: 'Full funnel from awareness reels to retargeting close',
    accentColor: '#2563EB',
    metrics: [
      { label: 'Total Revenue', value: '$220K' },
      { label: 'Time Frame', value: '6 months' },
      { label: 'Avg ROAS', value: '4.1x' },
    ],
    problem: 'Premium home décor brand struggling to find its audience on social media and convert traffic.',
    strategyDetail: 'Built a full TikTok funnel: lifestyle awareness content at the top, product demonstrations in the middle, aggressive retargeting with UGC testimonials at the bottom.',
    resultsDetail: '$220,000 in revenue over 6 months. 4.1x average ROAS. Brand awareness increased 5x measured by organic search volume.',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Karim B.',
    country: 'Morocco',
    flag: 'MA',
    stars: 5,
    text: "Walid transformed our store. Revenue tripled in 3 months. His ad knowledge is on another level. Best investment we've made for our business.",
    role: 'E-commerce Founder',
  },
  {
    id: 2,
    name: 'Sophie L.',
    country: 'France',
    flag: 'FR',
    stars: 5,
    text: "I came to him with a failing store. He rebuilt the entire strategy and now we're profitable every month. Couldn't recommend him enough.",
    role: 'Shopify Store Owner',
  },
  {
    id: 3,
    name: 'Ahmed R.',
    country: 'UAE',
    flag: 'AE',
    stars: 5,
    text: "Best product researcher I've worked with. Every product he recommends converts. He saved us from 3 bad launches and found us 2 winners.",
    role: 'Brand Manager',
  },
  {
    id: 4,
    name: 'Lena M.',
    country: 'Germany',
    flag: 'DE',
    stars: 5,
    text: 'His TikTok Shop strategy is pure fire. We went from 0 to 2,000 orders in 6 weeks. The ROI has been incredible.',
    role: 'TikTok Shop Seller',
  },
  {
    id: 5,
    name: 'Youssef T.',
    country: 'Algeria',
    flag: 'DZ',
    stars: 5,
    text: "Walid is the guy you want when you're serious about scaling. Professional, fast, results-driven. He delivers every time.",
    role: 'Dropshipping Operator',
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    slug: 'winning-products-research-system',
    title: 'How I Find Winning Products Before They Go Viral (My Full Research System)',
    category: 'Product Research',
    readTime: '8 min read',
    date: 'June 15, 2025',
    summary: "After testing 1,200+ products across multiple niches, I've developed a proprietary scoring system that consistently identifies winners before they hit mainstream. I break down my exact research stack — Minea, AdSpy, TikTok Creative Center — and the 7 criteria I score every product against.",
    content: `After testing 1,200+ products across multiple niches, I've developed a proprietary scoring system that consistently identifies winners before they hit mainstream.\n\n## The Research Stack\n\nI use a combination of tools to identify potential winners:\n\n**1. Minea for Trend Spotting**\nMinea allows me to see which products are getting heavy ad spend. When I see a product with 50+ active ads and recent launches, that's a signal.\n\n**2. AdSpy for Validation**\nAdSpy shows me how long ads have been running. If a product's ads have been running for 30+ days profitably, it's a strong validation signal.\n\n**3. TikTok Creative Center**\nThe hashtag analytics and trending products section often reveals what's about to go viral before it does.\n\n## My 7-Point Scoring System\n\n1. **Demand Signal** (0-2): Is there existing demand? Are people searching for this?\n2. **Wow Factor** (0-2): Does it stop someone mid-scroll?\n3. **Margin Potential** (0-2): Can we price it at 3x COG?\n4. **Market Size** (0-1): Is the audience large enough?\n5. **Competition Level** (0-1): Is the market oversaturated?\n6. **Ad Angle** (0-1): Are there obvious creative angles?\n7. **Trend Timing** (0-1): Early trend? Peak? Declining?\n\nA score of 7.5+ means we test it immediately.`,
  },
  {
    id: 2,
    slug: 'tiktok-shop-2025-playbook',
    title: 'TikTok Shop in 2025: The Complete Playbook for New Sellers',
    category: 'TikTok Shop',
    readTime: '12 min read',
    date: 'May 28, 2025',
    summary: "TikTok Shop has completely changed the e-commerce landscape and most sellers are still approaching it wrong. I cover product selection, affiliate outreach templates, content testing strategy, and the shop setup mistakes that kill conversions.",
    content: `TikTok Shop has fundamentally changed how products go from obscurity to $10K/day in sales. Here's how to do it right.\n\n## Why TikTok Shop is Different\n\nUnlike traditional e-commerce, TikTok Shop operates on entertainment-first, then conversion. Your product needs to be:\n- Visually demonstrable in 15-30 seconds\n- Priced for impulse purchase ($20-80 sweet spot)\n- Solving a visible problem or creating a wow moment\n\n## The First 30 Days Strategy\n\n**Days 1-7: Setup & Optimization**\n- Complete your shop profile 100%\n- Upload products with TikTok-native descriptions\n- Get your first 10 affiliate approvals\n\n**Days 8-21: Content Testing**\n- Post 2-3 organic videos daily\n- Test 5 different creative angles\n- Identify your top-performing hook\n\n**Days 22-30: Scale**\n- Double down on winning content\n- Launch first paid traffic with $50/day budget\n- Recruit 20+ affiliates for volume`,
  },
  {
    id: 3,
    slug: 'why-dropshippers-fail',
    title: 'Why 90% of Dropshippers Fail in Year 1 (And How to Be in the 10%)',
    category: 'Dropshipping',
    readTime: '10 min read',
    date: 'May 10, 2025',
    summary: "I've consulted with hundreds of aspiring dropshippers and I can tell you exactly why most fail — it's not the products, not the ads, not the competition. I break down the 5 most common failure patterns and the exact frameworks to avoid each one.",
    content: `I've consulted with hundreds of dropshippers. Here are the real reasons most fail.\n\n## Failure Pattern #1: Product Selection by Passion, Not Data\n\nThe biggest mistake: choosing products you personally like instead of what the market wants.\n\n**The fix**: Use data-driven product research. If you can't validate demand in Minea or AdSpy, don't test it.\n\n## Failure Pattern #2: Under-Capitalized Testing\n\nMost beginners stop testing after $200 of ad spend on a product. This isn't enough data.\n\n**The fix**: Budget $500 minimum per product test. If you can't afford 10 tests, don't start yet.\n\n## The 10% Framework\n\nTo be in the profitable 10%, you need:\n1. Data-driven product selection\n2. Capitalized testing budget ($5K minimum before launch)\n3. Systems for everything\n4. Focus on one store, one niche for the first 12 months\n5. Weekly analysis and iteration`,
  },
  {
    id: 4,
    slug: 'roas-formula-meta-ads',
    title: 'The ROAS Formula: How to Structure Meta Ads for Consistent 4x Returns',
    category: 'Meta Ads',
    readTime: '9 min read',
    date: 'April 22, 2025',
    summary: "A 4x ROAS on Meta isn't magic — it's math. I walk through my exact campaign structure for consistent returns: how I organize campaigns by funnel stage, my audience hierarchy, the creative testing protocol, and the bid strategy settings at each stage.",
    content: `After managing $380K+ in Meta ad spend, here's what actually drives consistent 4x+ ROAS.\n\n## Campaign Architecture\n\n**Layer 1: Cold Traffic (60% of budget)**\n- 5-6 separate ad sets with different audience types\n- Broad + interest-based + lookalike (1-3%)\n- Always 3+ creative variants per ad set\n\n**Layer 2: Warm Traffic (25% of budget)**\n- Video view retargeting (25%, 50%, 75%)\n- Website visitors (180-day)\n\n**Layer 3: Hot Traffic (15% of budget)**\n- Add-to-cart, initiate checkout\n- Past purchasers (LTV campaigns)\n\n## The 72-Hour Creative Test Protocol\n\n1. Launch 3 creative variants per ad set\n2. Wait 72 hours (minimum $50 spend each)\n3. Kill anything below 2x ROAS\n4. Double budget on winners\n5. Launch 2 new challengers weekly`,
  },
  {
    id: 5,
    slug: 'woocommerce-vs-shopify-2025',
    title: 'WooCommerce vs Shopify in 2025: Which One Should You Build On?',
    category: 'Store Setup',
    readTime: '7 min read',
    date: 'April 5, 2025',
    summary: "After building 23+ stores on both platforms, I have a definitive answer — but it's not what most people expect. I break down total cost of ownership, speed to market, scalability ceiling, and SEO capabilities with specific recommendations.",
    content: `After building 23+ stores on both platforms, here's my definitive comparison.\n\n## Total Cost of Ownership\n\n**Shopify:**\n- Basic: $39/month + 2% transaction fees\n- Professional plugins: +$200-500/month\n- True monthly cost: $400-800/month for a serious store\n\n**WooCommerce:**\n- Hosting: $30-80/month\n- Plugins: $100-300/month\n- True monthly cost: $630-1,380/month\n\n## My Current Recommendation\n\nFor most new e-commerce operators in 2025: start with Shopify. Once you hit $500K annual revenue, evaluate a WooCommerce migration for the SEO and margin benefits.`,
  },
];

export const ABOUT_TIMELINE = [
  { year: '2019', title: 'First Shopify Store', description: 'Launched first dropshipping store in the fashion niche. Made first $10K in revenue.' },
  { year: '2020', title: 'Meta Ads Mastery', description: 'Scaled first store to $40K/month using Facebook advertising. Reinvested everything.' },
  { year: '2021', title: 'Agency Formation', description: 'Started managing ad accounts for other e-commerce brands. Built first team.' },
  { year: '2022', title: 'TikTok Transition', description: 'Early mover on TikTok Ads and TikTok Shop. Generated $500K+ for clients.' },
  { year: '2023', title: 'Brand Building', description: 'Shifted focus to brand building and full-funnel strategy. Launched 10+ stores.' },
  { year: '2024', title: '$2M Milestone', description: 'Crossed $2M in total revenue generated across all managed accounts.' },
  { year: '2025', title: 'Global Expansion', description: 'Working with brands across 17 countries. Expanding into new markets.' },
];

export const TOOLS = [
  { name: 'Shopify', category: 'Platform' },
  { name: 'WooCommerce', category: 'Platform' },
  { name: 'Meta Ads Manager', category: 'Advertising' },
  { name: 'TikTok Ads', category: 'Advertising' },
  { name: 'Google Ads', category: 'Advertising' },
  { name: 'Minea', category: 'Research' },
  { name: 'AdSpy', category: 'Research' },
  { name: 'TikTok Creative Center', category: 'Research' },
  { name: 'Klaviyo', category: 'Email' },
  { name: 'Loox', category: 'Reviews' },
  { name: 'ReConvert', category: 'Upsell' },
  { name: 'Canva', category: 'Creative' },
];
